[project]
name = "resumegenie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.0",
    "langchain-google-genai>=4.4.0",
    "langgraph-checkpoint-postgres>=3.1.2",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "openevals>=0.2.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "streamlit>=1.63.0",
]
